version: "3.8"
services:

  backend:
    container_name: elt_backend
    build:
      context: .
      dockerfile: ./dockerfile-php7.yml
    ports:
      - 9000:9000
    volumes:
      - ./xml-guestbook:/app
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_enable=1

  redis:
    container_name: elt_redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  nginx:
    container_name: elt_nginx
    image: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./xml-guestbook:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
